name: Fancy Free
favicon: null
layout_spectrum: 1
typography_spectrum: 0.68631
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7edfd'
    - '#0c0d11'
    - '#ff0044'
    - '#b1a3b9'
    - '#685b51'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
