favicon: null
name: Fancy Free
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0.3125
  rhythmicContrast: 0
  brandColors:
    - '#e7edfd'
    - '#0c0d11'
    - '#ff0044'
    - '#b1a3b9'
    - '#685b51'
  lightness: 1
typography_spectrum: 0.10577
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.1812816
analytics:
  twitter: null
  google: null
  facebook: null
